### ISSUE TITLE
Upgrade to 21.1 error

### ISSUE THREAD

**Issue by SkilPhil** [linuxmint/mintupgrade#63] opened 2023-01-07 11:36 UTC
I have been trying to upgrade for a couple of days but keep getting the following error.
"Failed to fetch http://packages.linuxmint.com/dists/vera/InRelease 403 Forbidden [IP: 91.241.95.156 80]The repository 'http://packages.linuxmint.com/ vera InRelease' is not signed."
I have tried all available mirrors with the same result.

**Comment by carlosmintfan** [comment] 2023-01-07 20:52
Could you show me the output of:
`ls /etc/apt/trusted.gpg.d`
and:
`ls /usr/share/keyrings`
?

**Comment by dahav-eos** [comment] 2023-01-11 09:35
Same here:
`ls /etc/apt/trusted.gpg.d`:

7EA0A9C3F273FCD8.gpg  
google-chrome.gpg  
linuxmint-keyring.gpg  
linuxmint-keyring.gpg~  
ubuntu-defaults.chroot.key.gpg  
ubuntu-keyring-2012-cdimage.gpg  
ubuntu-keyring-2016-dbgsym.gpg  
ubuntu-keyring-2018-archive.gpg

`ls /usr/share/keyrings`:

docker-archive-keyring.gpg  
ubuntu-archive-keyring.gpg       
ubuntu-cloudimage-keyring.gpg       
ubuntu-dbgsym-keyring.gpg       
ubuntu-master-keyring.gpg
linuxmint-keyring.gpg       
buntu-archive-removed-keys.gpg  
ubuntu-cloudimage-removed-keys.gpg  
ubuntu-dbgsym-removed-keys.gpg

**Comment by carlosmintfan** [comment] 2023-01-11 21:08
Could you show me the full output of:
`apt-get update`
?

**Comment by SkilPhil** [comment] 2023-01-12 03:34
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

**Comment by SkilPhil** [comment] 2023-01-12 03:37
I did send the original request to your email. Not sure if I was to send it here.
Here it is.
 ls /etc/apt/trusted.gpg.d
linuxmint-keyring.gpg            ubuntu-keyring-2016-dbgsym.gpg
ubuntu-defaults.chroot.key.gpg   ubuntu-keyring-2018-archive.gpg
ubuntu-keyring-2012-cdimage.gpg

 ls /usr/share/keyrings
linuxmint-keyring.gpg            ubuntu-cloudimage-removed-keys.gpg
meganz-archive-keyring.gpg       ubuntu-dbgsym-keyring.gpg
ubuntu-archive-keyring.gpg       ubuntu-dbgsym-removed-keys.gpg
ubuntu-archive-removed-keys.gpg  ubuntu-master-keyring.gpg
ubuntu-cloudimage-keyring.gpg

**Comment by carlosmintfan** [comment] 2023-01-13 17:50
Ah sorry, please run **sudo** apt-get update
and please also the full output of the sudo mintupgrade command until the step where you're getting the error.

**Comment by SkilPhil** [comment] 2023-01-14 04:43
*sudo* apt-get update

Ign:1 https://mirror.wiru.co.za/linuxmint-packages vanessa InRelease 
Hit:2 https://mirror.wiru.co.za/ubuntu jammy InRelease 
Get:3 https://mirror.wiru.co.za/ubuntu jammy-updates InRelease [114 kB] 
Get:4 https://mirror.wiru.co.za/ubuntu jammy-backports InRelease [99.8 kB]
Hit:5 https://mirror.wiru.co.za/linuxmint-packages vanessa Release 
Get:6 https://mirror.wiru.co.za/ubuntu jammy-updates/main amd64 DEP-11 Metadata [97.1 kB]
Get:7 https://mirror.wiru.co.za/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [257 kB]
Get:9 https://mirror.wiru.co.za/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:10 https://mirror.wiru.co.za/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [11.5 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:12 https://mega.nz/linux/repo/xUbuntu_22.04 ./ InRelease [2,961 B]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [41.4 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [13.3 kB]
Fetched 749 kB in 3s (277 kB/s)
Reading package lists... Done


~$ sudo apt install mintupgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  avfs kactivities-bin kactivitymanagerd kde-cli-tools kde-cli-tools-data
  kio-extras kio-extras-data kpackagelauncherqml kpackagetool5 libappimage0
  libkdsoap1 libkf5activities5 libkf5activitiesstats1 libkf5auth5
  libkf5declarative-data libkf5declarative5 libkf5dnssd-data libkf5dnssd5
  libkf5kcmutils-data libkf5kcmutils5 libkf5kiofilewidgets5 libkf5package-data
  libkf5package5 libkf5pty-data libkf5pty5 libkf5quickaddons5 libkf5su-bin
  libkf5su-data libkf5su5 libkf5syntaxhighlighting-data
  libkf5syntaxhighlighting5 libkworkspace5-5 libsquashfuse0
  linux-headers-5.15.0-53 linux-headers-5.15.0-53-generic
  linux-headers-5.15.0-56 linux-headers-5.15.0-56-generic
  linux-image-5.15.0-53-generic linux-image-5.15.0-56-generic
  linux-modules-5.15.0-53-generic linux-modules-5.15.0-56-generic
  linux-modules-extra-5.15.0-53-generic linux-modules-extra-5.15.0-56-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  acpi crudini python3-iniparse
The following NEW packages will be installed:
  acpi crudini mintupgrade python3-iniparse
0 upgraded, 4 newly installed, 0 to remove and 7 not upgraded.
Need to get 150 kB of archives.
After this operation, 942 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://mirror.wiru.co.za/ubuntu jammy/universe amd64 acpi amd64 1.7-1.1ubuntu1 [13.0 kB]
Get:2 https://mirror.wiru.co.za/ubuntu jammy/universe amd64 python3-iniparse all 0.4-3 [20.1 kB]
Get:3 https://mirror.wiru.co.za/ubuntu jammy/universe amd64 crudini amd64 0.9.3-5 [15.3 kB]
Get:4 https://mirror.wiru.co.za/linuxmint-packages vanessa/main amd64 mintupgrade all 2022.08.13 [102 kB]
Fetched 150 kB in 6s (27.0 kB/s)
Selecting previously unselected package acpi.
(Reading database ... 494335 files and directories currently installed.)
Preparing to unpack .../acpi_1.7-1.1ubuntu1_amd64.deb ...
Unpacking acpi (1.7-1.1ubuntu1) ...
Selecting previously unselected package python3-iniparse.
Preparing to unpack .../python3-iniparse_0.4-3_all.deb ...
Unpacking python3-iniparse (0.4-3) ...
Selecting previously unselected package crudini.
Preparing to unpack .../crudini_0.9.3-5_amd64.deb ...
Unpacking crudini (0.9.3-5) ...
Selecting previously unselected package mintupgrade.
Preparing to unpack .../mintupgrade_2022.08.13_all.deb ...
Unpacking mintupgrade (2022.08.13) ...
Setting up acpi (1.7-1.1ubuntu1) ...
Setting up python3-iniparse (0.4-3) ...
Setting up crudini (0.9.3-5) ...
Setting up mintupgrade (2022.08.13) ...
Processing triggers for desktop-file-utils (0.26+mint1+vanessa) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for doc-base (0.11.1) ...
Processing 1 added doc-base file...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...

This reinstalls vanessa.

Running the update from the 'update manager' there is not log to record. The file list disappears when the error occurs. Just get the attached screenshot.
![error](https://user-images.githubusercontent.com/122155958/212451830-773549b8-8283-4c58-80e7-1193c451196a.png)

**Comment by carlosmintfan** [comment] 2023-01-14 18:18
Oh. You're upgrading from 21 to 21.1, right?
Then this issue should be moved to mintupdate.

**Comment by carlosmintfan** [comment] 2023-01-14 18:21
Make sure you have the latest version of linuxmint-keyring before upgrading. Does that help?

**Comment by carlosmintfan** [comment] 2023-01-14 18:23
If that doesn't work:
Run the following command in a terminal:
sudo cp /usr/share/mint-upgrade-info/vanessa/official-package-repositories.list /etc/apt/sources.list.d/official-package-repositories.list
Then, what does sudo apt-get update say?
Note: The above command sudo cp /usr/share... points your package repositories to Vera.
And it points your Mint and Ubuntu repos to packages.linuxmint.com/archive.ubuntu.com

**Comment by carlosmintfan** [comment] 2023-01-14 20:37
But your repositories should already point to Vera if you started to upgrade until the error came - if you didn't change your mirrors.

**Comment by clefebvre** [comment] 2023-01-19 11:16
I'll close this since this is a troubleshooting issue, not a bug per se.

Two quick ways to get back on your feet:

- Restore the system to the last functional snapshot using Timeshift
- Or go to mintsources -> Restore the default settings

You can use the forums to seek help while troubleshooting this issue, or alternatively if you want to chat live with people there's the IRC or the Discord. Give people the output of "inxi -r", along with the output of "apt update". This is the most relevant information.

**Closed as completed by clefebvre** 2023-01-19 11:16 UTC
