### ISSUE TITLE
Systemd units/timers discrepency between LMDE4 upgrade and LMDE5 install

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/mintupgrade#7] opened 2022-04-13 14:31 UTC
I have a recent VM install from the LMDE5 ISO and also an upgrade from LMDE4 -> LMDE5 (in another VM).
However, running **systemctl list-timers --all** reveals discrepancies:-
A) The ISO version runs **fstrim** and **plocate-updatedb** but not exim4-base or mlocate [which is correct].
B) The upgrade version runs **exim4-base** and **mlocate** but not **fstrim** or **plocate-updatedb** [almost certainly incorrect]

The upgrade version doesn't even install the plocate package, although fstrim is available, because it's part of a standard package.

Install from LMDE5 ISO
```
me@lmde5:~$ systemctl list-timers --all
NEXT                        LEFT          LAST                        PASSED             UNIT                         ACTIVATES
Wed 2022-04-13 13:37:56 BST 1min 41s left Wed 2022-04-13 13:28:23 BST 7min ago           anacron.timer                anacron.service
Wed 2022-04-13 14:30:51 BST 54min left    Fri 2022-03-18 01:43:09 GMT 3 weeks 5 days ago apt-daily.timer              apt-daily.service
Wed 2022-04-13 13:52:00 BST 15min left    Fri 2022-04-08 21:18:37 BST 4 days ago         apt-daily-upgrade.timer      apt-daily-upgrade.service
Sun 2022-04-17 03:10:47 BST 3 days left   Wed 2022-04-13 13:23:31 BST 12min ago          e2scrub_all.timer            e2scrub_all.service
Wed 2022-04-13 13:48:26 BST 12min left    Fri 2022-04-08 22:01:34 BST 4 days ago         fstrim.timer                 fstrim.service
Wed 2022-04-13 16:25:52 BST 2h 49min left Fri 2022-03-18 01:43:09 GMT 3 weeks 5 days ago fwupd-refresh.timer          fwupd-refresh.service
Wed 2022-04-13 13:49:47 BST 13min left    n/a                         n/a                systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Thu 2022-04-14 00:00:00 BST 10h left      Wed 2022-04-13 13:23:23 BST 12min ago          logrotate.timer              logrotate.service
Thu 2022-04-14 00:00:00 BST 10h left      Wed 2022-04-13 13:23:23 BST 12min ago          man-db.timer                 man-db.service
Thu 2022-04-14 00:45:28 BST 11h left      Thu 2022-03-24 15:59:05 GMT 2 weeks 5 days ago plocate-updatedb.timer       plocate-updatedb.service
```
.
.
Upgrade LMDE4 -> LMDE5
```
jeremy@lmde:~$ systemctl list-timers --all
NEXT                        LEFT          LAST                        PASSED        UNIT                         ACTIVATES
n/a                         n/a           Wed 2022-04-13 13:39:15 BST 3min 45s ago  anacron.timer                anacron.service
Wed 2022-04-13 20:37:37 BST 6h left       Tue 2022-04-12 23:49:44 BST 13h ago       apt-daily.timer              apt-daily.service
Wed 2022-04-13 14:06:25 BST 23min left    Tue 2022-04-12 23:49:44 BST 13h ago       apt-daily-upgrade.timer      apt-daily-upgrade.service
Sun 2022-04-17 03:10:27 BST 3 days left   Tue 2022-04-12 01:58:57 BST 1 day 11h ago e2scrub_all.timer            e2scrub_all.service
Thu 2022-04-14 00:00:00 BST 10h left      Wed 2022-04-13 00:00:00 BST 13h ago       exim4-base.timer             exim4-base.service
Wed 2022-04-13 18:03:51 BST 4h 20min left Tue 2022-04-12 01:59:38 BST 1 day 11h ago fwupd-refresh.timer          fwupd-refresh.service
Thu 2022-04-14 00:00:00 BST 10h left      Wed 2022-04-13 00:00:00 BST 13h ago       logrotate.timer              logrotate.service
Thu 2022-04-14 00:00:00 BST 10h left      Wed 2022-04-13 00:00:00 BST 13h ago       man-db.timer                 man-db.service
Thu 2022-04-14 00:00:00 BST 10h left      Wed 2022-04-13 00:00:00 BST 13h ago       mlocate.timer                mlocate.service
Wed 2022-04-13 13:54:01 BST 11min left    n/a                         n/a           systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
```

**Comment by clefebvre** [comment] 2022-04-14 09:01
plocate was added to LMDE 5 as a replacement for mlocate. That said, we don't really need to make that switch during upgrade. For exim, if it was installed there's no need to remove it, it's your system after all, the goal of the upgrade isn't to bring you back to what LMDE 5 fresh is, but to upgrade your system.

I'll check for fstrim.

**Comment by clefebvre** [comment] 2022-04-14 10:08
For fstrim I think it's because we don't usrmerge, we'll be fixing that.

**Comment by clefebvre** [comment] 2022-04-14 18:39
Afaik this isn't enabled by default during Debian upgrades.

In any case, I can confirm it had nothing to do with usrmerge (which is now fixed).

**Closed as completed** 2022-04-18 20:23 UTC
